# Generated by Django 3.0.9 on 2022-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_userregistrationmodel_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('idValue', models.IntegerField()),
                ('title', models.TextField(max_length=500)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
    ]
